# https://www.playframework.com/documentation/latest/Configuration
play.filters.enabled += "play.filters.csrf.CSRFFilter"
play.http.secret.key="V0sLX<RAciXw_>7^O8y=I4BRW/M4@vhVhF=H44`lMfgAV2hs^Pp?tsfroKt1J3eX"

slick.dbs.default.profile = "slick.jdbc.MySQLProfile$"
slick.dbs.default.db.driver = "com.mysql.cj.jdbc.Driver"
slick.dbs.default.db.url = "jdbc:mysql://localhost:3306/population_manager?serverTimezone=UTC&useSSL=false"
slick.dbs.default.db.user = "root"
slick.dbs.default.db.password = ""

cassandra {
  hosts = ["127.0.0.1"]
  port = 9042
  keyspace = "your_keyspace_name"
  username = "your_username"
  password = "your_password"
}
